global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    cluster: 'production'
    environment: 'prod'

scrape_configs:
  - job_name: 'loxilb-enterprise'
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: '/netlox/v1/metrics'
    static_configs:
      - targets:
          - '54.180.113.121:11111'  # Replace with your LoxiLB Enterprise IP and port
        labels:
          region: 'ap-northeast-2'
          datacenter: 'seoul2'